### ISSUE TITLE
nheko does not start when kzones installed

### ISSUE THREAD

**Issue by matthiasbeyer** [gerritdevriese/kzones#10]
I know this sounds weird, but it is exactly what I experienced.

I installed kzones via the system settings and then restarted my display session. "nheko" did not start after that. Removing kzones, restarting the display session again - everything works again!

**Comment by gerritdevriese** [comment]
I cannot reproduce this, can you give some more info about your system?
KWin logs would be handy as well: `kwin_x11 --replace & disown`

**Comment by matthiasbeyer** [comment]
> I cannot reproduce this, can you give some more info about your system?

What kind of info would you like to have? It is a NixOS stable running KDE 5.24.5!

**Comment by gerritdevriese** [comment]
Can you restart KWin in a terminal and take a look if you see any errors?
```
kwin_x11 --replace & disown
```

**Comment by gerritdevriese** [comment]
No response, closing.
