### ISSUE TITLE
Overlapping zone indicator offset

### ISSUE THREAD

**Issue by spacekatia** [gerritdevriese/kzones#102]
A i've been messing around with this plugin, i've come across the need to have two zones whose centers overlap. Naturally, i tried the method outlined in #1 but the `indicator` JSON object seems to not be evaluated. 

I'm on 

- Kzones 0.8
- Plasma 6.1.4
- Wayland

so i'm wondering if this just didn't get make the jump across plasma versions or of i'm going at this all wrong.

Either way, this is one of the most useful KDE plugins for me - thank you for the excellent work :>

**Comment by gerritdevriese** [comment]
This option was scrapped a while ago, but I'll re-add for you in the next version 🙂

**Comment by gerritdevriese** [comment]
Not sure if you still need this, but you can now specify the position of the indicator

- `indicator`: an object containing the indicator settings (optional)
  - `position`: default is `center`, other options are `top-left`, `top-center`, `top-right`, `right-center`, `bottom-right`, `bottom-center`, `bottom-left`, `left-center`
  - `margin`: an object containing the margin for the indicator
    - `top`, `right`, `bottom`, `left`: margin in pixels

Maybe it's a bit overkill but I think now you can move the indicator anywhere you want.

For example to move it 50 pixels down:

```json
{
    "x": 0,
    "y": 0,
    "height": 100,
    "width": 25,
    "indicator": {
        "margin": {
            "top": 50
        }
    }
}
```
