### ISSUE TITLE
Preferred or selected layout not being saved or remembered

### ISSUE THREAD

**Issue by SuperSweatyYeti** [gerritdevriese/kzones#103]
Thank you for this amazing script.  We are so close to having feature parity with FancyZones for Windows because of you :)

**Describe the bug**
Layout is not being saved or preserved on reboot or logoff.

**To Reproduce**
Cycle through layouts with assigned shortcut and select one that is NOT the first layout in the JSON layouts file.

Reboot or logoff/logon.

Zone layout will default to the first layout in the JSON layouts section.

Layout is not being saved either when selecting "Track active layout per screen" or when it is unselected.

**Expected behavior**
Preferred layout will be saved and used on next reboot or login.

**Screenshots**
N/A

**System information  (please complete the following information):**
 - KZones version 0.9
 - Plasma version 6.1.4
 - Wayland
 - Fedora Linux 40

**Comment by gerritdevriese** [comment]
> Thank you for this amazing script. We are so close to having feature parity with FancyZones for Windows because of you 

Thanks, that's the objective 🙂

> Preferred layout will be saved and used on next reboot or login.

Sadly this is currently not possible in the KWin API, there is no way to save the config at runtime nor did I find an (acceptable) workaround to save data, sorry 😐
