### ISSUE TITLE
No work determine zone for cursor method with indicator target

### ISSUE THREAD

**Issue by imKYW** [gerritdevriese/kzones#11]
Kzone ver : 0.4
...
KDE Plasama ver: 5.25.5
KDE Frameworks ver:  5.98
QT ver: 5.15.6
Kernel ver: 5.19.13-arch1-1 (64bit)
Graphics Platform: X11
...
no work determine zone for cursor method with indicator target.
i think work in kzone 0.2

btw, ty for awesome kwin script.

**Comment by gerritdevriese** [comment]
Are you sure you have xdotool installed?
https://github.com/gerritdevriese/kzones#caveats

**Comment by imKYW** [comment]
> Are you sure you have xdotool installed? https://github.com/gerritdevriese/kzones#caveats

oh! work after install `xdotool`!
tyvm!
