### ISSUE TITLE
[Feature request] Allow snapping to multiple zones when dragging the window onto the edge between multiple zones

### ISSUE THREAD

**Issue by fightforlife** [gerritdevriese/kzones#116]
**Is your feature request related to a problem? Please describe.**
I recently switched from Windows to Kubuntu.
On windows I always installed http://windowgrid.net/ first.
It is quite similiar to kzones and kzones really helped me feelt at home in kde.
There are two features that I am missing:
1. Snapping a windows to multiple zones. e.g. having a grid of 3 horizontall x 2 vertical zones. In Windowgrid it was possible to to drag a windows into any zone but also extend it to multiple zones in x or y direction. This was really helpful when I wanted to read a longer page. I did not have to change the grid, but just extend the windows into multiple zones.
2. Having the right mouse key as a snapping shortcut while dragging window was really intuitive. (might be possible already, did not check yet)

**Describe the solution you'd like**
I would like to drag a window on the edge between two zones and have it extend to both zones.

**Describe alternatives you've considered**
Multiple grid is working, but having all the different variations of grids is quite cumbersome.

**Additional context**
See/try http://windowgrid.net/

**Comment by gerritdevriese** [comment]
I get what you mean but this isn't in the scope for KZones.
Seem like a fun idea to work out in a different script though. Shouldn't be too hard using the built-in plasma tiling API.

**Comment by fightforlife** [comment]
For anyone fonding this. I found two solutions to this problem FR:
1. create multiple grids: 3x2, 3x1, 2x2, etc. Then you can always choose the correct size.
2. create one grid with overlapping zones whcih only get acitvated when hovering above the indiciator. With this you can have all variations in one grid.

```
[
    {
        "name": "3x2 Grid with overlapp",
        "zones": [
            {
                "x": 0,
                "y": 0,
                "height": 50,
                "width": 33.333
            },
            {
                "x": 33.333,
                "y": 0,
                "height": 50,
                "width": 33.333
            },
            {
                "x":66.666,
                "y": 0,
                "height": 50,
                "width": 33.333
            },
            {
                "x": 0,
                "y": 50,
                "height": 50,
                "width": 33.333
            },
            {
                "x": 33.333,
                "y": 50,
                "height": 50,
                "width": 33.333
            },
            {
                "x": 66.666,
                "y": 50,
                "height": 50,
                "width": 33.333
            },
            {
                "x": 0,
                "y": 0,
                "height": 100,
                "width": 33.333
            },
            {
                "x": 33.333,
                "y": 0,
                "height": 100,
                "width": 33.333
            },
            {
                "x": 66.666,
                "y": 0,
                "height": 100,
                "width": 33.333
            },
            {
                "x": 0,
                "y": 0,
                "height": 100,
                "width": 66.666
            },
            {
                "x": 33.333,
                "y": 0,
                "height": 100,
                "width": 66.666
            },
            {
                "x": 0,
                "y": 0,
                "height": 50,
                "width": 66.666
            },
            {
                "x": 33.333,
                "y": 0,
                "height": 50,
                "width": 66.666
            },
            {
                "x": 0,
                "y": 50,
                "height": 50,
                "width": 66.666
            },
            {
                "x": 33.333,
                "y": 50,
                "height": 50,
                "width": 66.666
            }            
        ]
    }
]

```
