### ISSUE TITLE
Visually differentiate layouts + zones

### ISSUE THREAD

**Issue by spiffytech** [gerritdevriese/kzones#119]
**Is your feature request related to a problem? Please describe.**
My layouts are tricky to tell apart at a glance. Some are mirror images of each other, and KZones' compact, black-on-gray design makes it hard to quickly tell which zones go with which layouts, without looking closely.

![image](https://github.com/user-attachments/assets/df0d1c8c-eebc-4b6e-9dbf-207772660e7f)

**Describe the solution you'd like**
Here are a few ideas:
1. Allow the user to color-code each zone. Here, I've done it by size, but a user could do whatever they want.
2. Allow a user to label a zone. Here, I've used single-letter labels because that's adequate for my needs and it's easy to fit one letter into the current design.
3. Improve the color contrast between background and foreground, or maybe add dividers between zones. This could be combined with either of the above

![kzones](https://github.com/user-attachments/assets/c815829b-7ef6-4720-ba82-db5f3d5bbfcc)
 
All the colors I picked are awful, don't use them :slightly_smiling_face: Maybe the user can pick a hex code?

**Describe alternatives you've considered**
Layout definitions include a `name` field which I don't see displayed right now. Displaying that would be a start, but I feel that would still be suboptimal for telling at a glance which layout I wanted, since reading is slower than e.g., noticing colors.

**Comment by gerritdevriese** [comment]
I tried your first idea in [this branch](https://github.com/gerritdevriese/kzones/tree/color-rework), you can add a color key to a zone with a color name (blue, red, etc..) or a hex value:

```json
[
    {
        "x": 0,
        "y": 0,
        "height": 50,
        "width": 50,
        "color": "purple"
    },
    {
        "x": 0,
        "y": 50,
        "height": 50,
        "width": 50,
        "color": "#ab2ec7"
    }
]
```

Are you able to clone/build to test?

The contrast depends on your Plasma theme, the default Breeze theme doesn't have a lot of contrast between Buttons and views. I'll try out some things though in said branch to try and improve this.

**Comment by gerritdevriese** [comment]
I think i fixed the contrast issue. I tried a bunch of themes and it seems a lot better now.

**Comment by spiffytech** [comment]
I've installed from the branch, here's what I see:
![image](https://github.com/user-attachments/assets/6ea8213b-ffdb-4363-b505-8847d9c9070a)
![image](https://github.com/user-attachments/assets/dd246765-f2bb-4601-8962-07c78ceab888)
![image](https://github.com/user-attachments/assets/60ec9bc3-5a8f-4bbc-a4cb-4942dc3c4891)


I think the darker background helps, even without customizing the zone colors.

Directionally, I think this is working well. It feels much easier to find the layout I want.

It looks like KZones is dimming the zone colors? Reminds me of dead flowers :cry:

I see they light up when selected, but still don't seem to be the color I specified. Seems like the fully-illuminated color should match the hex code I configured.

![image](https://github.com/user-attachments/assets/87110753-4f92-4e0e-a955-b56e4714c87c)

I'm not sure what (if anything) should be done about the color dimming. It makes sense for the overlay — highlighting each zone is the obvious thing to do. For the selector... maybe make them all bright, then dim when you hover over one? But then it works different from the overlay, which isn't great, and I don't know how that looks on dark themes or with dark zone colors. Or maybe just leave it as-is? I don't know.

**Comment by gerritdevriese** [comment]
I dimmed the colors so you can easily differentiate between highlighted and non-highlighted zones, that's why they look a bit dull and don't match the exact hex. Also in dark mode a full 100% of the color is bit too bright so I set it to about 80%

If you think of it more like a "tint" instead of "color" it makes a bit more sense.

**Comment by spiffytech** [comment]
Alright, sounds good to me. Thanks for implementing this!
