### ISSUE TITLE
Please add layout config validation

### ISSUE THREAD

**Issue by yacoob** [gerritdevriese/kzones#120]
Thanks for creating kzones - it keeps my sanity safe :)

**Is your feature request related to a problem? Please describe.**
I've added one more extra comma past the last element of a list in my layout config editbox. The resulting string was no longer a valid JSON. 

**Describe the solution you'd like**
It would be nice for kzones to pop up a message about this. Right now it just silently fails to start.

**Comment by gerritdevriese** [comment]
This should be already solved in the main branch (not released yet), if you make a mistake in the JSON it will fallback to the default layout and display an error message.

Though it's not tested by anyone other then myself, so if you can [build the git version](https://github.com/gerritdevriese/kzones?tab=readme-ov-file#build-it-yourself) and give feedback that would be great 🙂
