### ISSUE TITLE
Starting Games often leads to OSD overlaying the entire screen

### ISSUE THREAD

**Issue by erikroe** [gerritdevriese/kzones#14]
In some games (i.e. Warthunder, Guild Wars 2, and more) as soon as I start them (the actual game, not their Launchers) the complete screen is being overlayed by the OSD. I did not call the OSD. Nor can I interact with it. Alt+Tab shows me the Window Switcher of KDE, but it does never let the OSD overlay disappear – regardless what other window i pick. Only killing the actual game with Alf+F4 solves the issue.
This is a serious issue because if a game does not react to Alt+F4 I must restart my entire computer via the hardware button. There is no way I can interact with the system's UI anymore using the cursor.

As soon as I tell KZones to not restore geometry via the KDE System Settings it does work. But then i have a black rectangle on the top left which is about 100px wide and 30px high in every of those games instead.

System info:

Operating System: Nobara Linux 36
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.16-201.fsync.fc36.x86_64 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 5700
Manufacturer: Micro-Star International Co., Ltd
Product Name: MS-7C02
System Version: 1.0

Screen resolution: 3840x1600

**Comment by gerritdevriese** [comment]
Not sure why this is happening. The restore geometry thing makes it even weirder.
Are you switching to a different resolution in these games? (as opposed to borderless windowed mode)

**Comment by erikroe** [comment]
Those games run in Borderless Window Mode each. Another that I had tested was in regular Fullscreen however. The resolution in those games is all the same native one as my desktop is. I also do not have any secondary screens.

**Comment by diederikgist** [comment]
I'm experiencing this same issue as well. When I start up Counterstrike Source (part of the Steam platform) the OSD kicks in with a full black background. Nothing much I can do, with Control Alt D I can interact a bit with Kzones as it will switch between my layouts but the OSD with black background stays on top, I do hear the background sounds of the game though. I normaly go to a terminal (control alt f2), kill steam, go back to KDE and now everying is working normaly again. I then disable Kzones and start Counterstrike. Then if I don't forget enable Kzones again after playing. 

I'm having this issues on my laptop at the main screen, but also when I connect it to my ultra wide screen at home or my dual screens at the office. Laptop screen is always off when I use a seperate monitor.

System info:

Operating System: KDE neon 5.26
KDE Plasma Version: 5.26.2
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 5.15.0-52-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-10210U CPU @ 1.60GHz
Memory: 62.2 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: HP
Product Name: HP EliteBook 840 G7 Notebook PC

**Comment by MattyGWS** [comment]
Can confirm, I just tried to play a game in full screen and all I could see were my zones and black, game loaded but wasn't visible. :(

**Comment by codeswhite** [comment]
I was able to reproduce it on X11.

@MattyGWS @diederikgist @erikroe 
Are any of you experience this on Wayland? 

---

I have wrote (PR #25 ) a solution for this and would like you guys to test it out on your systems as well, especially on Wayland if its reproducible on Wayland as well.

Note: that i was working from top of the `test` branch.

**Comment by erikroe** [comment]
@codeswhite Built your version of it and the error is indeed gone. I unfortunately have no Wayland at hand to verify it there.

**Comment by codeswhite** [comment]
Good, you can use my fork for a lot more fixes.

**Comment by gerritdevriese** [comment]
To fully fix this issue I recommend turning off the following Plasma setting: Display and Monitor - Compositor - Allow applications to block compositing.

Let me know if that also fixes it for you.

**Comment by diederikgist** [comment]
Toggling off that option fixed it. Didn't check other solution from @codeswhite as I'm running X11, not Wayland.

**Comment by wolflarson** [comment]
Disabling compositing does fix this for me as well. You can also use the old Alt + Shift + F12 to toggle it as the issue is occurring (when I start the game) then back on after you exit the game. 

I have not used KDE while compositing is disabled for long enough to know for sure but the forums / reddit talk about stuttering and panel update issues while off. 

Operating System: Manjaro Linux
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 5.15.85-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C56
System Version: 2.0
