### ISSUE TITLE
OSD wrong size

### ISSUE THREAD

**Issue by joaophi** [gerritdevriese/kzones#15]
### First of all, awesome project!

I'm having some weird bug, sometimes the OSD doesn't pick the right screen size and I have restart the script a few times until it gets right.

System Info:
KDE 5.26.1
Linux 6.0.2
Arch linux
Wayland

- OSD small in the top left corner

![Screenshot_20221021_125333](https://user-images.githubusercontent.com/23062105/197240670-bc0087c5-6048-44ca-b20f-a648c8868380.png)

- Connecting to a external display keeps the old screen size

![Screenshot_20221021_130504](https://user-images.githubusercontent.com/23062105/197240677-f288dd8c-09b6-406e-9328-abbfc2882631.png)

**Comment by gerritdevriese** [comment]
I will look into this, I haven't really tested much on Wayland yet.

**Comment by Niiisse** [comment]
This happens for me too!

**Comment by gerritdevriese** [comment]
Can you try the latest version? (you need Plasma > 5.27)
