### ISSUE TITLE
Plugin does not provide configuration file in expected location

### ISSUE THREAD

**Issue by Knochi** [gerritdevriese/kzones#17]
Hi,

installed via discover on steam deck (modified Arch Linux with KDE Plasma Desktop). 
I can see the OSD but not get the windows snapped to it.
In Settings app i could not find "kZones" settings, but it's there under "Workspace"--> "Window Management"-->"KWin Scripts"
When i hit the "Configure" button i get an error message

![image](https://user-images.githubusercontent.com/5979046/197390217-b62fb739-6630-488c-bd8e-ba7e979c3054.png)

System Information:
Operating System: SteamOS 3.3.2
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve21.3-1-neptune (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14,5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405

**Comment by gerritdevriese** [comment]
This bug seems to exist on versions before Plasma 5.24.0

https://bugs.kde.org/show_bug.cgi?id=444378

I already added the X-KDE-ConfigModule "fix" to the metadata, but this doesn't work on your version.

Is it possible for you to update your plasma version to something above 5.24.0?

**Comment by Knochi** [comment]
Guess not, since it‘s a kind of package, bundled in this steam OS. Maybe there is a a way but then it will revert with next SteamOS update.

**Comment by gerritdevriese** [comment]
Closing due to this being a (resolved) KWin issue.
