### ISSUE TITLE
[Question] How to disable on an individual monitor

### ISSUE THREAD

**Issue by itz4blitz** [gerritdevriese/kzones#18]
I'm trying to figure out if there's a way to disable kzones on an individual monitor. Currently I have my layout with a 3 monitor setup. My setup has a 32" center monitor with a 24" monitor in portrait orientationon each side of the monitor in the center:

![image](https://user-images.githubusercontent.com/60281870/198495912-7d3a3904-c889-4dd5-840f-955cee98cdd7.png)

For the outside monitors I created the following `Layout 2`:

```json
[
    {
        "name": "Layout 1",
        "padding": 0,
        "zones": [
            {
                "name": "1",
                "x": 0,
                "y": 0,
                "height": 100,
                "width": 25
            },
            {
                "name": "2",
                "x": 25,
                "y": 0,
                "height": 100,
                "width": 50
            },
            {
                "name": "3",
                "x": 75,
                "y": 0,
                "height": 100,
                "width": 25
            }
        ]
    },
    {
        "name": "Layout 2",
        "padding": 0,
        "zones": [
            {
                "name": "1",
                "x": 0,
                "y": 0,
                "height": 33,
                "width": 100
            },
            {
                "name": "2",
                "x": 0,
                "y": 33,
                "height": 34,
                "width": 100
            },
            {
                "name": "3",
                "x": 0,
                "y": 66,
                "height": 33,
                "width": 100
            }
        ]
    }

]
```

I would like the center monitor to either 1) use Layout 1 instead of taking the Layout which I've setup for the outside monitors, or 2) to disable KZones on monitor 1 (if possible). Thanks, and awesome project.

**Comment by gerritdevriese** [comment]
This is not possible at the moment, but hopefully in the future if and when #4 gets implemented.
