### ISSUE TITLE
Plasma 5.20.5: Settings not shown (Minor issue)

### ISSUE THREAD

**Issue by dionysius** [gerritdevriese/kzones#21]
Installed via KDE Store. I can't really find an exact expression of the version requirement. We only have from the Readme: "Check if your KDE version is up to date.". I am [currently stuck to 5.20.5](https://packages.debian.org/bullseye/plasma-desktop).

The Kzones script so far works fine! I could update the keyboard shortcuts and per default it seems to come with a 3 zone layout. It just doesn't show the settings button:
![Screenshot_20221104_145313](https://user-images.githubusercontent.com/1341084/199989332-3fd4e31f-0518-448e-b13d-cbfcc8be7963.png)

I could modify the config by hand, but the UI settings would be more intuitive for the start. I also can't find anything wrong at a glance comparing that config file with another kwin script:

```
$ head -n 10 .local/share/kwin/scripts/kzones/contents/config/main.xml 
<?xml version="1.0" encoding="UTF-8"?>
<kcfg xmlns="http://www.kde.org/standards/kcfg/1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.kde.org/standards/kcfg/1.0
      http://www.kde.org/standards/kcfg/1.0/kcfg.xsd" >
    <kcfgfile name=""/>
    <group name="">

        <entry name="rememberWindowGeometries" type="Bool">
            <default>true</default>
```
```
$ head -n 10 .local/share/kwin/scripts/mudeer-ultrawide/contents/config/main.xml 
<?xml version="1.0" encoding="UTF-8"?>
<kcfg xmlns="http://www.kde.org/standards/kcfg/1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.kde.org/standards/kcfg/1.0
      http://www.kde.org/standards/kcfg/1.0/kcfg.xsd" >
  <kcfgfile name=""/>
  <group name="">
    <entry name="middleIncrease" type="int">
      <label>Increase in pixels of width of middle slot in 3 slot setup</label>
      <default>0</default>
```

Anyone an idea what could be the cause for the missing settings button? Or where to look for debug output? Maybe kwin doesn't understand a settings type or so...

**Comment by gerritdevriese** [comment]
Hi, please refer to issue #17
This bug exists on versions before Plasma 5.24.0, and there is no way for me to fix it in the script, sorry.
