### ISSUE TITLE
Meta+Mouse move shows indicators, but does not move window

### ISSUE THREAD

**Issue by artshade** [gerritdevriese/kzones#22]
Dear Developers,

Thank you very much for the great project.

---

Evidently, when using `Meta + Mouse Left Button` to move a window the indicators are shown, but zones do not highlight and the windows does no move to the zone. What might it be?

It's worth to mention that the OS built-in snapping works.

---

The affected OS:
```
Operating System: KDE neon 5.26
KDE Plasma Version: 5.26.2
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 5.15.0-52-generic (64-bit)
Graphics Platform: X11
```

---

Related: [KDE Tip: Resize Window with a Mouse + Key Combo](https://www.reddit.com/r/kde/comments/i1bm2i/comment/fzvyfbj/?utm_source=share&utm_medium=web2x&context=3)

Best and kind regards :sparkles:

**Comment by codeswhite** [comment]
Please try the `test` branch, supposed to be fixed there

**Comment by gerritdevriese** [comment]
Same issue as #16
