### ISSUE TITLE
Non-Primary mouse button includes all buttons incl. `LMouse`

### ISSUE THREAD

**Issue by codeswhite** [gerritdevriese/kzones#27]
With this feature on, when i start moving a window with Super+LMouse,
It detects the mouse button LMouse as pressed and always shows the OSD, even if its configured to show only by a modifier key when moving/dragging.

I would like to be able to configure the non-primary button in the config, so that only when pressing RMouse the OSD will show.

**Comment by gerritdevriese** [comment]
Modifier keys have been removed from the project for now.
