### ISSUE TITLE
Fullscreen games break when kzones enabled

### ISSUE THREAD

**Issue by wolflarson** [gerritdevriese/kzones#34]
I'm not really sure how to gather details as to whats going on but I can replicate it every time. 

Enable KZones. 
Start Steam
Start fullscreen game
All screens go black showing the KZones screen dragging icon and the mouse. Audio continues to work. After the game loads I can alt+f4 to quit the game (or switch tty and kill steam) and things return to normal. 

My game only opens on one monitor but my other monitor goes black as well. 

Disable KZones, start game all issues resolved.

**Comment by gerritdevriese** [comment]
Please try the following: https://github.com/gerritdevriese/kzones/issues/14#issuecomment-1336378222

> To fully fix this issue I recommend turning off the following Plasma setting: Display and Monitor - Compositor - Allow applications to block compositing.
> 
> Let me know if that also fixes it for you.

**Comment by wolflarson** [comment]
Duplicate of https://github.com/gerritdevriese/kzones/issues/14
