### ISSUE TITLE
Does not track moving windows between screens using shortcuts

### ISSUE THREAD

**Issue by jjspace** [gerritdevriese/kzones#36]
I have a two monitor setup and I very often move windows between my screens using shortcuts. By default in Kubuntu 22.04 these are `Meta+Shift+Right/Left`.

![2023-02-07_11-01](https://user-images.githubusercontent.com/8007967/217297228-830de943-6928-4437-9b25-de6dd07484a6.png)

Kzones does not seem to be able to track this change and when I try to assign a location for the window using the kzones shortcut it jumps back to the previous screen _and_ location. 

For example I have a 2/3rds zone as zone 1 and 1/3rd zone as zone 2 set up horizontally. 

1. Window 1 is on screen 1
2. Press `Meta+Shift+Right` to move window 1 to screen 2
3. Press `Ctrl+Alt+Num 2` to put it in zone 2
4. The window shifts back to screen 1 in zone 2 on that screen
5. Drag window 1 to screen 2 with the mouse
6. Press `Ctrl+Alt+Num 2` to put it in zone 2
7. The window aligns into zone 2 on screen 2

Because of #4 this same layout applies to all screens. I'm ok with this fact but I feel that it should always respect the screen the window is _currently on_. If I move the window across screens with the mouse, whether or not I drag it directly into the OSD zones, it will react as I expect it to using the kzones shortcuts.

**Comment by trivoldus28** [comment]
@jjspace Should be fixed now with the merge

**Comment by jjspace** [comment]
Tested quickly and seems to work as expected. Thank you @trivoldus28!
