### ISSUE TITLE
Cannot find the "Layouts tab in the script settings"

### ISSUE THREAD

**Issue by terry-permeance** [gerritdevriese/kzones#37]
I've installed the KWin script under System Settings but cannot find the "Layouts tab in the script settings" as described in the docs. 

![image](https://user-images.githubusercontent.com/2471270/223101271-7a8d417b-e67b-439c-9954-0edc572dd558.png)

I can see a default 1:2:1 layout is installed using CTRL+ALT+LEFT and CTRL+ALT+RIGHT.

Is there some application to edit the "Layouts tab in the script settings"? I am using Ubuntu 18.04 and plasmashell 5.18.8. Since others have no such problem and Google isn't helping me, this must be a newbie question so apologies in advance.

Thanks,
Terry

**Comment by gerritdevriese** [comment]
I remember this was an issue in older versions of KDE, as documented here for example:
https://github.com/kwin-scripts/kwin-tiling/issues/79

You can try the following fix:

```
mkdir -p ~/.local/share/kservices5/
ln -s ~/.local/share/kwin/scripts/kzones/metadata.desktop ~/.local/share/kservices5/kzones.desktop
```

Or manually editing the config file located here: `~/.config/kwinrc`

Of course, upgrading your system would also do the trick.

**Comment by terry-permeance** [comment]
Hello,

I've upgraded to Ubuntu 22.04 and can now see the settings.

Thanks,
Terry
