### ISSUE TITLE
Switch to next window in current zone within the current workspace

### ISSUE THREAD

**Issue by dwarfi09** [gerritdevriese/kzones#38]
Hi, thank you so much for this wonderful script!

The shortcut "Switch to next window in current zone" switches across all workspaces. Could we have an option to switch to next window in current zone *within* current workspace?

**Comment by trivoldus28** [comment]
I second this request. Currently it also switches across activities, so it'd be great if we can have the option to switch per workspace and per activity. Keep up the great work btw!

**Comment by trivoldus28** [comment]
@dwarfi09 I managed to hack together an implementation that does this in this pull req https://github.com/gerritdevriese/kzones/pull/45
