### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by imthenachoman** [gerritdevriese/kzones#40]
I was wondering if there are plans to add mouse support for WayLand? Right now it says it's not supported?

**Comment by gerritdevriese** [comment]
When https://github.com/gerritdevriese/kzones/pull/23 is merged into the main branch it will be supported.
If you don't want to wait for that you can use their fork for now: https://github.com/apfelkuchen6/kzones

**Comment by imthenachoman** [comment]
Out of curiosity, anything stopping it from being merged in?
