### ISSUE TITLE
Mouse dragging to zone isn't working

### ISSUE THREAD

**Issue by Quantamm** [gerritdevriese/kzones#41]
I'm seeing this in both X11 and Wayland. I'm running KDE 5.27 on OpenSUSE Tumbleweed. When I drag a window by the titlebar, the OSD appears, but when I put the mouse cursor in the OSD area and let go, the window isn't resized.

I can use ctrl-alt-left to move the window into a zone. And I can use ctrl-alt-c to show the OSD and then click on the OSD to move the window to that zone.

**Comment by gerritdevriese** [comment]
On X11 you should have `xdotool` installed (https://github.com/gerritdevriese/kzones#caveats)
Wayland mouse support is coming soon.

**Comment by Quantamm** [comment]
Thanks for the quick reply. I already had `xdotool` installed, so that's not it.

I thought that maybe this is an OpenSUSE issue, so I grabbed the latest KDE Neon live image (https://files.kde.org/neon/images/user/20230518-0715/neon-user-20230518-0715.iso) and am able to reproduce the issue there on two separate machines.

Steps to reproduce:
- Start the KDE Neon live install
- Open a terminal and run "sudo apt install xdotool"
- Go to KDE Settings, Display and Monitor, Compositor. Ensure "Enable on startup" is on and turn "Allow applications to block compositing" off.
- Go to KDE Settings, Window Management, KWin Scripts, Get New Scripts, and install KZones.
- Logout (which on the live image will automatically log you back in.
- Open Firefox and drag it by the titlebar. The three OSD Zone indicators will appear.
- Drag the mouse cursor to any of the three and let go. Firefox will not be snapped to the zone.

`loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type` confirms that I am running x11.

**Comment by c-schaer** [comment]
I'm having the same issue with a new install of kubuntu. Verified that I'm using x11 and installed `xdotool` and restarted, dragging any window shows the zone indicators but windows will not snap to the zones. KDE Plasma version 5.24.7

**Comment by gerritdevriese** [comment]
The latest version should work on Wayland and X11 w/o xdotool, provided you have Plasma 5.27 or above
