### ISSUE TITLE
[Feature request] Switch between windows on the same zone

### ISSUE THREAD

**Issue by juacq97** [gerritdevriese/kzones#5]
Hi! Loving your extension!! After trying other scripts I feel this is the best combination between tiling and stacking window management yet.  There's a feature I'd like to see implemented, you can put many windows on the same zone, the windows will be one on top of the other, it could be possible to switch between windows on the same zone with a keybinding (even better, a dbus command)? This will be something similar to have tabs like i3/sway and very useful at least to me. I don't know how difficult that could be, or even if it's possible, but I would love to see that feature on kzones

**Comment by gerritdevriese** [comment]
Hi, thanks for the suggestion, I added the following shortcuts:

| Shortcut                                      | Default Binding           |
|-----------------------------------------------|---------------------------|
| Switch to previous window in current zone     | `Ctrl+Alt+Down`           |
| Switch to next window in current zone         | `Ctrl+Alt+Up`             |

It's currently in the test branch, so you can already try it if you want.

As for dbus, you should be able to invoke KWin shortcuts like this:
```
qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "KZones: Toggle OSD"
```
