### ISSUE TITLE
Touchscreen Compatibility

### ISSUE THREAD

**Issue by k4ever** [gerritdevriese/kzones#52]
Is there any way to add/re-add touchscreen compatibility? I used KZones on my Surface Pro 8 a few months ago and it worked great when moving windows with a touchscreen. However, lately it doesn't seem to work with a touchscreen. The top drag zone indicator will only show with a mouse and I can only drag windows to one zone when using the touchscreen (the one on the right side of the screen). I don't know what changed, but touchscreen compatibility is completely broken in later versions.

Edit: Forgot to list:
Hardware: Microsoft Surface Pro 8
OS: EndeavourOS
Kernel: 6.4.12-arch1-1-surface
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
QT Version: 5.15.10

**Comment by gerritdevriese** [comment]
Hi, are you using Wayland or X11?

**Comment by k4ever** [comment]
I apologize for not listing that. I'm using Wayland.

**Comment by gerritdevriese** [comment]
You are right, I'm getting the same behavior.
This is probably because the scripting API doesn't return a cursorPos when using a touchscreen (previously we used xdotool for this) https://github.com/gerritdevriese/kzones/pull/23

I'm not sure when I will be able to solve this, in the meantime you can maybe use the old version?

**Comment by k4ever** [comment]
> You are right, I'm getting the same behavior. This is probably because the scripting API doesn't return a cursorPos when using a touchscreen (previously we used xdotool for this) #23
> 
> I'm not sure when I will be able to solve this, in the meantime you can maybe use the old version?

I apologize. I was on vacation for a week and just saw your post last night. Which older version do you recommend (please provide a link)? I tried a few older versions and either still had the issue or the version didn't work well with Wayland at all. I can't remember the version that worked well.

**Comment by gerritdevriese** [comment]
You can find all versions here: https://github.com/gerritdevriese/kzones/releases
Everything before v0.5 used the old position system, so v0.4 should work (granted you use Titlebar or Window as zone determine method)

**Comment by slimx** [comment]
0.4 doesn't work either

**Comment by gerritdevriese** [comment]
Which "Target method" are you using? Only Titlebar or Window will work as xdotool isn't supported on Wayland.
