### ISSUE TITLE
Toggle overlay without moving window

### ISSUE THREAD

**Issue by Klounita** [gerritdevriese/kzones#53]
On version 0.4 i was able to show overlay by shortcut then click on any zone and active window moves to it. It was awesome. On current version (0.6) it doesnt work because overlay dont appear if i dont move window. Please add this feature

**Comment by gerritdevriese** [comment]
This feature was removed because the way the osd was rendered before caused some issues with the compositor. Now we use the "OnScreenDisplay" window type which doesn't support mouse pass-through.
