### ISSUE TITLE
trigger OSD with a mouse button 

### ISSUE THREAD

**Issue by jbtrystram** [gerritdevriese/kzones#54]
Thanks for this excellent script :) 

Would it be possible to have the OSD show up with a mouse button ? 
Ideally, if I would move a window using the middle click, the OSD would show, if using regular left click, no OSD. 
That would avoid pressing a complex shortcut while moving windows

**Comment by gerritdevriese** [comment]
It is not possible (anymore) to respond to mouse actions in the KWin API.

Btw, you can also trigger the overlay like this if that helps:

```
qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "KZones: Toggle zone overlay"
```
