### ISSUE TITLE
Windows gets snapped to unrelated zone

### ISSUE THREAD

**Issue by codeswhite** [gerritdevriese/kzones#55]
A bug when using `[Ctrl+Alt+Left \ Right]` to move a client that has no zone (`client.zone == -1`).
Results in an unexpected snapping to unrelated zones.
Instead, it would be preferred to snap to either the closest or the most overlapping zone.

https://github.com/gerritdevriese/kzones/blob/e5de36c51974cc28aa672218ef4bcc5a8c47754e/contents/ui/main.qml#L246

**Comment by gerritdevriese** [comment]
This should be solved now
