### ISSUE TITLE
How to permanently disable OSD?

### ISSUE THREAD

**Issue by DuckInspector** [gerritdevriese/kzones#59]
I cannot manage to permanently disable the OSD, is it possible? I tried messing with the main.qml file in the UI folder but with no luck.

**Comment by gerritdevriese** [comment]
You can disable the OSD in the script settings by unchecking "Enable Zone Overlay"

**Comment by DuckInspector** [comment]
My bad, I had not updated in a while so I didn't have that setting... Thanks!
