### ISSUE TITLE
this plugin causes kwin_x11 to spike up in CPU

### ISSUE THREAD

**Issue by mdarweash** [gerritdevriese/kzones#61]
once this script is enabled, CPU usage goes up to 50 to 70% (kwin_x11) and xorg

let me know what type of logs or details you need to help on debugging and fixing this

regards

**Comment by gerritdevriese** [comment]
Can you do the following:

- Disable the script
- Run `kwin_x11 --replace & disown` in a terminal
- Re-enable the script and see if it throws any errors or warnings in the terminal

Do you also experience this issue on Wayland?
