### ISSUE TITLE
KZones v0.7 is being offered as an upgrade, on a Plasma 5 system when it is Plasma 6 only?

### ISSUE THREAD

**Issue by abclution** [gerritdevriese/kzones#64]
Debian 12 is offering me this as an upgrade on my KDE Plasma 5 system when the release notes mention this is only Plasma 6 compatible.  Could the author please clarify?

**Comment by gerritdevriese** [comment]
While updating the store page I changed the category from Plasma 5 to 6, seems that wasn't enough to block the update.
I created a separate page for Plasma 5: https://www.pling.com/p/2143914, so you can install that one instead and you won't get further updates.
