### ISSUE TITLE
[Enhancement] Theming support with Plasma Styles

### ISSUE THREAD

**Issue by AlphaCraft9658** [gerritdevriese/kzones#67]
It would be cool if the Zone selector or other widgets of this script would follow the Plasma Style or could be themed with it. There could also be a toggle in the script settings, which lets the user decide whether the script should use its default styling or the user's Plasma Style. The main reason I got this idea is that the widget is sadly not translucent and blurred as the rest of my setup is, and doesn't quite fit it. It's an amazing script, but this would be a neat addition I and probably some other users would really appreciate.

**Comment by gerritdevriese** [comment]
It should already follow your theme as much as the API currently supports.
Can you provide a screenshot so I have a better understanding of what you mean?

**Comment by AlphaCraft9658** [comment]
> It should already follow your theme as much as the API currently supports. Can you provide a screenshot so I have a better understanding of what you mean?

My Plasma Style has a lot of transparency, which doesn't apply to the zone selector.
![image](https://github.com/gerritdevriese/kzones/assets/77483478/a2ade102-e21b-49ab-955d-07b332e61144)
Unless the Plasma Style has to manually implement additional theming parameters for this specific widget.

**Comment by gerritdevriese** [comment]
I haven't found a (rational) way to do blurring, so it will never fully fit in with your theme.
If you want to tinker maybe you can try editing the opacity values in the QML file.

**Comment by AlphaCraft9658** [comment]
> I haven't found a (rational) way to do blurring, so it will never fully fit in with your theme.
> If you want to tinker maybe you can try editing the opacity values in the QML file.

Alright. 👍
