### ISSUE TITLE
[Feature Request] Option to disable both Drag & Drop and OSD

### ISSUE THREAD

**Issue by Nathorr** [gerritdevriese/kzones#7]
First of all thank you for this great script! If it is possible please add an option to disable Drag & Drop and OSD completely. I've created 13 zones for myself and I like to move windows around using keyboard shortcuts only. Sometimes I need to drag some smaller windows with my mouse and they get snapped to those zones by mistake.

I know that drag & dropping is one of the main features of this script. It is working great and I feel a bit silly asking this but what can you do.

**Comment by gerritdevriese** [comment]
I added an "inverted mode" for this, when enabled, moving windows will not trigger the osd. Instead you'll have to use the "Toggle OSD" shortcut to show the osd.
