### ISSUE TITLE
feature ideas for kzones

### ISSUE THREAD

**Issue by imthenachoman** [gerritdevriese/kzones#75]
I have some feature ideas for kzones. I didn't want to open multiple issues so I'm putting them all in one issue. 

- Add layout name to the top slide-down zone selector
- Show the top slide-down zone selector when cycling through layouts and highlight the active/selected one (replacing the current cycle layouts box): Some of us don't alway remember what a layout looks like by the name. So when we're cycling layouts, it would be good to see a visual of the layouts.
- Allow selecting a specific zone from any of the layout boxes when you have zone overlay active: With the zone overlay, you have to move the window to/near the zone you want to move to. If you're on one end of the screen on an ultrawide, that's a long distance the mouse has to go. Instead, when you show the overlay, if you could go to the closest layout box and then select a zone in that layout box, that would mean less mouse travel. I can explain more if this is confusing.
- Keyboard shortcuts for going forward/backward or next/previous when you're cycling layouts: like alt+tab and alt+shift+tab
- Use right mouse click to cycle through layouts when you're in the zone overlay (while moving a window to resize)
- A special keyboard shortcut to cycle layouts but only when zone overlay is active: I know the `Cycle layouts` works when the overlay is active but it would be nice to send a simpler shortcut, like ctrl, when the zone overlay is active. You wouldn't want ctrl to be the normal shortcut -- only when the overlay is active
- Keyboard shortcuts to select a zone when the overlay is active: When the overlay is active, each zone could have a customizable single letter keyboard shortcut to quickly select that zone. I can elaborate if needed.

**Comment by imthenachoman** [comment]
Added one more.

**Comment by gerritdevriese** [comment]
> Add layout name to the top slide-down zone selector

I don't really see the point of this, but if this is added it should be disabled by default.

> Show the top slide-down zone selector when cycling through layouts and highlight the active/selected one (replacing the current cycle layouts box): Some of us don't alway remember what a layout looks like by the name. So when we're cycling layouts, it would be good to see a visual of the layouts.

This is good idea 👍 I'll look into this.

> Allow selecting a specific zone from any of the layout boxes when you have zone overlay active: With the zone overlay, you have to move the window to/near the zone you want to move to. If you're on one end of the screen on an ultrawide, that's a long distance the mouse has to go. Instead, when you show the overlay, if you could go to the closest layout box and then select a zone in that layout box, that would mean less mouse travel. I can explain more if this is confusing.

I understand what you mean, this shouldn't be to hard to implement, but is low priority.

> Keyboard shortcuts for going forward/backward or next/previous when you're cycling layouts: like alt+tab and alt+shift+tab

This has been added, along with some extra shortcuts.

> Use right mouse click to cycle through layouts when you're in the zone overlay (while moving a window to resize)

Currently impossible with the KWin API.

>   A special keyboard shortcut to cycle layouts but only when zone overlay is active: I know the `Cycle layouts` works when the overlay is active but it would be nice to send a simpler shortcut, like ctrl, when the zone overlay is active. You wouldn't want ctrl to be the normal shortcut -- only when the overlay is active

Same as above, KWin scripts do not have access to the keyboard state, only predefined shortcuts are allowed.

>   Keyboard shortcuts to select a zone when the overlay is active: When the overlay is active, each zone could have a customizable single letter keyboard shortcut to quickly select that zone. I can elaborate if needed.

Would be nice, but also impossible 😢

**Comment by imthenachoman** [comment]
Awesome. Thank you so much!

**Comment by kupiqu** [comment]
Let me add another idea in the context of automatically tiling new windows. If the current state of the desktop can be monitored, something like the following working automatically would be awesome. 

First, set the tile profile, for instance 4 tiles showing quarter tiling, then, according to the state transition (previous state -> new state):

- empty desktop -> just one tile ocuppies the whole desktop
- one tile -> two vertical tiles
- two vertical tiles -> three tiles (narrow | wide| narrow)
- three tiles -> four tiles (quarter tiling)

What happens when in a desktop with 4 tiles already:

- four tiles -> four tiles (quarter tiling) + move the new window to the closer desktop with room space (up to 4 tiles) and behave depending on the above transitions
- if no desktop is available, create a new one and show one tile

**Comment by kupiqu** [comment]
Right now the different modalities can be configured easily in kzones, for dynamic tiling, we would need to establish the sequence, that could be set with the names showing the order as new tiles are added, e.g., {Single, Dual Grid, Priority Grid, Quadrant Grid}

**Comment by gerritdevriese** [comment]
@kupiqu I understand, but at that point we're just creating another tiling script like [Polonium](https://github.com/zeroxoneafour/polonium). That's not the objective of KZones.

**Comment by imthenachoman** [comment]
I also don't like the idea of my windows auto moving and sizing when I open a new window/app. I like to be in control of where I put them.

**Comment by kupiqu** [comment]
> I also don't like the idea of my windows auto moving and sizing when I open a new window/app. I like to be in control of where I put them.

Dynamic tiling would be optional, of course, but I understand it may be out of the scope of @gerritdevriese's intention for kzones.

I know Bismuth and Polonium, but never managed them to work. In plasma 5, I used quarter tiling, which was close to what I wrote above. While this worked for me, it was not flexible in the tiling options as Kzones could be, plus it doesn't work in Plasma 6.

**Comment by jendrew** [comment]
Hi. I'd like to add one more small idea, but first I'd like to thank you for your work - this tool is great. I've been using PowerToys on Windows, then gSnap on Gnome, and when I switched to Plasma 6 i found default tiling tool lacking. Your tool is much more powerful. 

However one thing I would add is the behavior  I like in the above tools - the ability to display the overlay ONLY when the shortcut is pressed, in the other words: the overlay would be active only while dragging the window and simultaneously having the shortcut button down. In my opinion that would make your tool even more usable, and also enable users to choose very simple shortcuts, like Control or Shift.

**Comment by gerritdevriese** [comment]
> However one thing I would add is the behavior I like in the above tools - the ability to display the overlay ONLY when the shortcut is pressed, in the other words: the overlay would be active only while dragging the window and simultaneously having the shortcut button down. In my opinion that would make your tool even more usable, and also enable users to choose very simple shortcuts, like Control or Shift.

You can kinda already achieve this in the current version:

![image](https://github.com/user-attachments/assets/742de94f-de2a-46a1-9d4a-ffe1a73bf84f)

Although it behaves like a normal "press to activate" shortcut, not "holding down the key".

Also since one of the latest versions of Plasma you can now choose modifier keys as shortcuts, so in theory you could set Control or Shift to show the KZones overlay in conjunction with the above mentioned setting.

**Comment by jendrew** [comment]
> > However one thing I would add is the behavior I like in the above tools - the ability to display the overlay ONLY when the shortcut is pressed, in the other words: the overlay would be active only while dragging the window and simultaneously having the shortcut button down. In my opinion that would make your tool even more usable, and also enable users to choose very simple shortcuts, like Control or Shift.
> 
> You can kinda already achieve this in the current version:
> 
> ![image](https://private-user-images.githubusercontent.com/1899386/365360966-742de94f-de2a-46a1-9d4a-ffe1a73bf84f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDY4NzksIm5iZiI6MTcyNTcwNjU3OSwicGF0aCI6Ii8xODk5Mzg2LzM2NTM2MDk2Ni03NDJkZTk0Zi1kZTJhLTQ2YTEtOWQ0YS1mZmUxYTczYmY4NGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDdUMTA1NjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdhYTQxMjI0YmQzOTc2MjIzZTkzMjVlMTdhZDgyNDRhNGI1NjcwNzE4YjVhMmRkZDk5M2EzYTlmMGJlYmEyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W7BE2wkpWxSibe7SaSmFSB4Q3ozYyzjnd8DtyAHpFFU)
> 
> Although it behaves like a normal "press to activate" shortcut, not "holding down the key".
> 
> Also since one of the latest versions of Plasma you can now choose modifier keys as shortcuts, so in theory you could set Control or Shift to show the KZones overlay in conjunction with the above mentioned setting.

Thanks! I have one issue with this setting - whenever I press Ctrl while NOT simultaneously dragging the window, the toast message appears stating that the toggle button works only when dragging a window. This behavior prevents me from using common key like Ctlr or Shift as a toggle button.

**Comment by gerritdevriese** [comment]
> Thanks! I have one issue with this setting - whenever I press Ctrl while NOT simultaneously dragging the window, the toast message appears stating that the toggle button works only when dragging a window. This behavior prevents me from using common key like Ctlr or Shift as a toggle button.

I'll see if I can add an option to disable OSD messages in the next version.

**Comment by jendrew** [comment]
I love it! Thanks!

**Comment by gerritdevriese** [comment]
I split some of the to-be-implemented features into separate issues, so closing this one.
