### ISSUE TITLE
Moving to zone with shortcut does not un-maximize window

### ISSUE THREAD

**Issue by jjspace** [gerritdevriese/kzones#78]
When moving windows into kzones zones using shortcuts from being maximized it does not switch the status of the window. This creates unexpected behavior the next time you try and maximize the window because it's already considered max so it shrinks instead.

(as another side effect, windows that change the border based on maximized status will not add the border when put in a zone like this. VSCode is the main/first one I noticed this on)

### Reproduce

- open any window
- press `Meta + Up` to maximize window
- press a shortcut to send the window to a zone
    - notice the window _does_ resize nicely but is still considered "maximized"
- press `Meta + Up` again and notice it does _not_ go to the maximized size because it thinks it already was. This results in it shrinking or changing position instead of the expected behavior of filling the screen.
- You can also watch the little "maximize or minimize" icon at the top of most applications to see what "state" it's in

**Comment by gerritdevriese** [comment]
Hi, thanks for reporting this.
The latest commit on the development branch should solve this issue.
