### ISSUE TITLE
Script Does Nothing - KDE Plasma Version 5.27.5

### ISSUE THREAD

**Issue by gooeybea** [gerritdevriese/kzones#82]
Unfortunately there is not very much to say here; the script simple does nothing. 
The settings window will open, the script will appear in the kwin script list, it will appear as enabled, however beyond showing the configuration menus and the ability to check or uncheck the script on the list, the script does nothing.

no zone overlays are displayed, the zone selector at the top of the screen isn't there, there aren't even any errors. it is functionally as if the script is not installed at all.

Script seems to have randomly stopped working about a 7+ days ago, not sure what happened, as I haven't touched anything in the settings for months. 

![image](https://github.com/gerritdevriese/kzones/assets/175268612/bd428dc9-ae38-4e89-8731-c0c617bcd4a1)

**Comment by gerritdevriese** [comment]
Is it possible that the script was updated somehow? https://github.com/gerritdevriese/kzones?tab=readme-ov-file#auto-update-broke-kzones-on-plasma-5

**Comment by gooeybea** [comment]
I just went through all of the older versions and had the same thing happen in all cases, unfortunately. 

Configuration window opens, it will allow me to edit config settings, i can "enable" it in kwin scripts, but ultimately it will not do anything else.

**Comment by gerritdevriese** [comment]
Can you try the following:
- Uninstall KZones using the script manager
- Open `~/.config/kwinrc` and remove all the settings under the header `[Script-kzones]`
- Remove the `kzones` folder from  `~/.local/share/kwin/scripts/` if it's still there
- Reboot
- Use the script manager to reinstall KZones (make sure it says "KZones for Plasma 5")
- Disable the script, click apply, enable and hit apply again

**Comment by eltoncezar** [comment]
I was facing the same issue on Plasma 5.24. After I upgraded to Plasma 5.27.11 everything started working.
