### ISSUE TITLE
Script doesn't work when move windows to the top

### ISSUE THREAD

**Issue by SMUEric1127** [gerritdevriese/kzones#87]
Hi there, 

I installed, at first I thought it didn't work since I moved the windows to the top and it would just maximize to the whole screen. However, looking up the shortcut and give them a try actually snapped into the zone. But again, moving the windows (even though showed the overlay) to the top is still maximizing the whole windows. Any fix? Thanks

**Comment by gerritdevriese** [comment]
As far as i know there is not such feature in KZones. Perhaps you mean the [Zone Selector](https://github.com/gerritdevriese/kzones?tab=readme-ov-file#zone-selector)? It should appear at the top of the screen and you can drag your window in one of the zones to snap them.

**Comment by gerritdevriese** [comment]
FYI, This feature will be included in the next release: https://github.com/gerritdevriese/kzones?tab=readme-ov-file#edge-snapping
