### ISSUE TITLE
Kwin freezes when Automatically snap all new windows is enabled

### ISSUE THREAD

**Issue by the-boar** [gerritdevriese/kzones#92]
Kzones 0.8
KDE Plasma 6.1.3

Whenever I enable the new feature "Automatically snap all new windows", the next time I try to move a window Kwin freezes up and I have to restart.

(Thanks for your work on this, I really enjoy kzones.)

**Comment by gerritdevriese** [comment]
This only seems to happen on Wayland and with a certain amount of open windows.
Something to look into for sure.

**Comment by gerritdevriese** [comment]
Fix pushed to main branch
