### ISSUE TITLE
can't start using kzones after installing the script

### ISSUE THREAD

**Issue by kyrollos-saad** [gerritdevriese/kzones#95]
i can't use it, nothing appears on the screen, nor there is a way to set a keyboard shortcut to activate kzones.
i can't find kzones in system shortcut settings.
noting happens when i move any window.

![image](https://github.com/user-attachments/assets/92760d11-ae26-440b-b4cd-4f1f00084c9f)

**environment:**
![image](https://github.com/user-attachments/assets/11996db9-7bce-4f9f-83cb-ddbe7da97722)

**Comment by gerritdevriese** [comment]
- I suppose you already tried to restart your system after installing?
- Does this also happen when running in Wayland?
- Can you share the contents of the layouts tab?

**Comment by kyrollos-saad** [comment]
> * I suppose you already tried to restart your system after installing?
> * Does this also happen when running in Wayland?
> * Can you share the contents of the layouts tab?

oooouh that's embarrassing 😬😬😬😬
yeah, restart did the trick

**Comment by gerritdevriese** [comment]
This is actually a bug in the Plasma 5 version of KZones, so not really your fault 😉
