### ISSUE TITLE
Layour per monitor

### ISSUE THREAD

**Issue by SoyDiego** [gerritdevriese/kzones#96]
is it possible detect or remember the a configured layout per monitor?
For example I have a vertical monitor and another horizontal and always I need to go to the top and choose the layout.
I would like to avoid and try to remember per monitor or the last configuration used in each monitor.

I don't know if this is possible or i'm asking for a new feature.

thanks again @gerritdevriese you are doing a great job!

**Comment by gerritdevriese** [comment]
Addressed in https://github.com/gerritdevriese/kzones/issues/4
