### ISSUE TITLE
Unwanted interaction between kzones and macsimize6

### ISSUE THREAD

**Issue by kupiqu** [gerritdevriese/kzones#97]
Please see this issue: https://github.com/Ubiquitine/MACsimize6/issues/9

Apparently Kzones "maximizes windows at some point during the zone assignment", which consequently triggers macsimize6.

If that is indeed the case, I don't fully understand why just dragging a window changes its maximization status. Could this be managed somehow differently in kzones so it behaves more friendly with the macsimize script? Otherwise I'd need to stop using one of the two scripts. I hope this can be alleviated somehow. 

Thanks in advance!

**Comment by gerritdevriese** [comment]
> Apparently Kzones "maximizes windows at some point during the zone assignment", which consequently triggers macsimize6.

It doesn't, I think it's the full screen KZones overlay that's causing this.
I commented on the mentioned issue with a possible fix.

**Comment by kupiqu** [comment]
I don't think it's the full screen, as I disabled that option, I only use the maximize option
